<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
    <RootNamespace>DeviceDrivers.Modbus</RootNamespace>
    <AssemblyName>DeviceDrivers.Modbus</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NModbus" Version="3.0.83" />
  </ItemGroup>

</Project>
