//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FProductionDashBoard.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FProductionDashBoard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Please loaded at least one device! 的當地語系化字串。
        /// </summary>
        internal static string AddDeviceNonSelectionError {
            get {
                return ResourceManager.GetString("AddDeviceNonSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Added 的當地語系化字串。
        /// </summary>
        internal static string ComStrAdded {
            get {
                return ResourceManager.GetString("ComStrAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Device 的當地語系化字串。
        /// </summary>
        internal static string ComStrDevice {
            get {
                return ResourceManager.GetString("ComStrDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Downloaded 的當地語系化字串。
        /// </summary>
        internal static string ComStrDownloaded {
            get {
                return ResourceManager.GetString("ComStrDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        internal static string ComStrErrorTitle {
            get {
                return ResourceManager.GetString("ComStrErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product 的當地語系化字串。
        /// </summary>
        internal static string ComStrProduct {
            get {
                return ResourceManager.GetString("ComStrProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Removed 的當地語系化字串。
        /// </summary>
        internal static string ComStrRemoved {
            get {
                return ResourceManager.GetString("ComStrRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System User 的當地語系化字串。
        /// </summary>
        internal static string ComStrSystemUser {
            get {
                return ResourceManager.GetString("ComStrSystemUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Time Slot 的當地語系化字串。
        /// </summary>
        internal static string ComStrTimeSlot {
            get {
                return ResourceManager.GetString("ComStrTimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Uploaded 的當地語系化字串。
        /// </summary>
        internal static string ComStrUploaded {
            get {
                return ResourceManager.GetString("ComStrUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User 的當地語系化字串。
        /// </summary>
        internal static string ComStrUser {
            get {
                return ResourceManager.GetString("ComStrUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warning 的當地語系化字串。
        /// </summary>
        internal static string ComStrWarningTitle {
            get {
                return ResourceManager.GetString("ComStrWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Device Card Management 的當地語系化字串。
        /// </summary>
        internal static string DeviceCardManageDialog {
            get {
                return ResourceManager.GetString("DeviceCardManageDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Result For Current First Inspection 的當地語系化字串。
        /// </summary>
        internal static string DeviceFirstInsDialog {
            get {
                return ResourceManager.GetString("DeviceFirstInsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Chenged Materials 的當地語系化字串。
        /// </summary>
        internal static string DeviceMaterialDialog {
            get {
                return ResourceManager.GetString("DeviceMaterialDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current Operation 的當地語系化字串。
        /// </summary>
        internal static string DeviceOperationDialog {
            get {
                return ResourceManager.GetString("DeviceOperationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Result For Current Routine Inspection 的當地語系化字串。
        /// </summary>
        internal static string DeviceRoutineInsDialog {
            get {
                return ResourceManager.GetString("DeviceRoutineInsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm 的當地語系化字串。
        /// </summary>
        internal static string DialogBaseConfirm {
            get {
                return ResourceManager.GetString("DialogBaseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        internal static string DialogBaseDelete {
            get {
                return ResourceManager.GetString("DialogBaseDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        internal static string DialogBaseSave {
            get {
                return ResourceManager.GetString("DialogBaseSave", resourceCulture);
            }
        }

        internal static string SopValidationStation {
            get {
                return ResourceManager.GetString("SopValidationStation", resourceCulture);
            }
        }

        internal static string SopValidationFixture {
            get {
                return ResourceManager.GetString("SopValidationFixture", resourceCulture);
            }
        }

        internal static string SopValidationOther {
            get {
                return ResourceManager.GetString("SopValidationOther", resourceCulture);
            }
        }

        internal static string SopValidationRequiredFields {
            get {
                return ResourceManager.GetString("SopValidationRequiredFields", resourceCulture);
            }
        }

        internal static string SopValidationMinItems {
            get {
                return ResourceManager.GetString("SopValidationMinItems", resourceCulture);
            }
        }

        internal static string SopSuccessAdd {
            get {
                return ResourceManager.GetString("SopSuccessAdd", resourceCulture);
            }
        }

        internal static string SopSuccessUpdate {
            get {
                return ResourceManager.GetString("SopSuccessUpdate", resourceCulture);
            }
        }

        internal static string SopTitleNew {
            get {
                return ResourceManager.GetString("SopTitleNew", resourceCulture);
            }
        }

        internal static string SopTitleEdit {
            get {
                return ResourceManager.GetString("SopTitleEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 First Inspection Abnormal, please report according to procedure! 的當地語系化字串。
        /// </summary>
        internal static string InsFirstAbnormal {
            get {
                return ResourceManager.GetString("InsFirstAbnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product updated, please do first inspection! 的當地語系化字串。
        /// </summary>
        internal static string InsFirstProductUpdate {
            get {
                return ResourceManager.GetString("InsFirstProductUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 First inspection is finished! 的當地語系化字串。
        /// </summary>
        internal static string InsFirstSuccess {
            get {
                return ResourceManager.GetString("InsFirstSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Routine inspection ended! 的當地語系化字串。
        /// </summary>
        internal static string InsRoutineEnd {
            get {
                return ResourceManager.GetString("InsRoutineEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Routine inspection overdue! 的當地語系化字串。
        /// </summary>
        internal static string InsRoutineOverdue {
            get {
                return ResourceManager.GetString("InsRoutineOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Routine inspection started! 的當地語系化字串。
        /// </summary>
        internal static string InsRoutineStart {
            get {
                return ResourceManager.GetString("InsRoutineStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Routine inspection is finished! 的當地語系化字串。
        /// </summary>
        internal static string InsRoutineSuccess {
            get {
                return ResourceManager.GetString("InsRoutineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Routine lights are updated! 的當地語系化字串。
        /// </summary>
        internal static string InsRoutineUpdateLight {
            get {
                return ResourceManager.GetString("InsRoutineUpdateLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading, please wait… 的當地語系化字串。
        /// </summary>
        internal static string LoadingInitMessage {
            get {
                return ResourceManager.GetString("LoadingInitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid account or password! 的當地語系化字串。
        /// </summary>
        internal static string LogInAccountError {
            get {
                return ResourceManager.GetString("LogInAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please check the connection! 的當地語系化字串。
        /// </summary>
        internal static string LogInConnectionError {
            get {
                return ResourceManager.GetString("LogInConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please fill out completely! 的當地語系化字串。
        /// </summary>
        internal static string LogInFillOutError {
            get {
                return ResourceManager.GetString("LogInFillOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Detecting... 的當地語系化字串。
        /// </summary>
        internal static string MainProgressDetecting {
            get {
                return ResourceManager.GetString("MainProgressDetecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System is idle... 的當地語系化字串。
        /// </summary>
        internal static string MainProgressIdle {
            get {
                return ResourceManager.GetString("MainProgressIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Processing... 的當地語系化字串。
        /// </summary>
        internal static string MainProgressProcessing {
            get {
                return ResourceManager.GetString("MainProgressProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Saving... 的當地語系化字串。
        /// </summary>
        internal static string MainProgressSaving {
            get {
                return ResourceManager.GetString("MainProgressSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stopped 的當地語系化字串。
        /// </summary>
        internal static string MainProgressStopped {
            get {
                return ResourceManager.GetString("MainProgressStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finished 的當地語系化字串。
        /// </summary>
        internal static string MainProgressSuccess {
            get {
                return ResourceManager.GetString("MainProgressSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select at least one item! 的當地語系化字串。
        /// </summary>
        internal static string MaterialNonSelectionError {
            get {
                return ResourceManager.GetString("MaterialNonSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Swipe card to confirm end of tuning 的當地語系化字串。
        /// </summary>
        internal static string TuningCardConfirm {
            get {
                return ResourceManager.GetString("TuningCardConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Tuning Operation 的當地語系化字串。
        /// </summary>
        internal static string TuningDialogTitle {
            get {
                return ResourceManager.GetString("TuningDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm end Offset? 的當地語系化字串。
        /// </summary>
        internal static string TuningEndConfirmOffset {
            get {
                return ResourceManager.GetString("TuningEndConfirmOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm end Teaching? 的當地語系化字串。
        /// </summary>
        internal static string TuningEndConfirmTeaching {
            get {
                return ResourceManager.GetString("TuningEndConfirmTeaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Offset... 的當地語系化字串。
        /// </summary>
        internal static string TuningInProgressOffset {
            get {
                return ResourceManager.GetString("TuningInProgressOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Teaching... 的當地語系化字串。
        /// </summary>
        internal static string TuningInProgressTeaching {
            get {
                return ResourceManager.GetString("TuningInProgressTeaching", resourceCulture);
            }
        }

        internal static string EqprodValidationEquipment {
            get {
                return ResourceManager.GetString("EqprodValidationEquipment", resourceCulture);
            }
        }

        internal static string EqprodValidationProduct {
            get {
                return ResourceManager.GetString("EqprodValidationProduct", resourceCulture);
            }
        }

        internal static string EqprodValidationProcess {
            get {
                return ResourceManager.GetString("EqprodValidationProcess", resourceCulture);
            }
        }

        internal static string EqprodValidationSeqNo {
            get {
                return ResourceManager.GetString("EqprodValidationSeqNo", resourceCulture);
            }
        }

        internal static string EqprodValidationSeqNoDuplicate {
            get {
                return ResourceManager.GetString("EqprodValidationSeqNoDuplicate", resourceCulture);
            }
        }

        internal static string EqprodValidationNoSop {
            get {
                return ResourceManager.GetString("EqprodValidationNoSop", resourceCulture);
            }
        }

        internal static string NoCurrentProduct {
            get {
                return ResourceManager.GetString("NoCurrentProduct", resourceCulture);
            }
        }

        internal static string OrderListTitle {
            get {
                return ResourceManager.GetString("OrderListTitle", resourceCulture);
            }
        }

        internal static string OnlyOneProductionError {
            get {
                return ResourceManager.GetString("OnlyOneProductionError", resourceCulture);
            }
        }

        internal static string ConfirmCancelOrder {
            get {
                return ResourceManager.GetString("ConfirmCancelOrder", resourceCulture);
            }
        }
    }
}
