//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FProductionDashBoard.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FProductionDashBoard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 ✓ Configured 的當地語系化字串。
        /// </summary>
        internal static string AboutApiKeyConfigured {
            get {
                return ResourceManager.GetString("AboutApiKeyConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ✗ Not Configured 的當地語系化字串。
        /// </summary>
        internal static string AboutApiKeyNotConfigured {
            get {
                return ResourceManager.GetString("AboutApiKeyNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ✓ Installed 的當地語系化字串。
        /// </summary>
        internal static string AboutSdkInstalled {
            get {
                return ResourceManager.GetString("AboutSdkInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ✗ Not Installed 的當地語系化字串。
        /// </summary>
        internal static string AboutSdkNotInstalled {
            get {
                return ResourceManager.GetString("AboutSdkNotInstalled", resourceCulture);
            }
        }

        internal static string LicenseStatusDevelopment {
            get { return ResourceManager.GetString("LicenseStatusDevelopment", resourceCulture); }
        }

        internal static string LicenseStatusValid {
            get { return ResourceManager.GetString("LicenseStatusValid", resourceCulture); }
        }

        internal static string LicenseStatusValidExpiringSoon {
            get { return ResourceManager.GetString("LicenseStatusValidExpiringSoon", resourceCulture); }
        }

        internal static string LicenseStatusExpired {
            get { return ResourceManager.GetString("LicenseStatusExpired", resourceCulture); }
        }

        internal static string LicenseStatusInvalidSignature {
            get { return ResourceManager.GetString("LicenseStatusInvalidSignature", resourceCulture); }
        }

        internal static string LicenseStatusTrial {
            get { return ResourceManager.GetString("LicenseStatusTrial", resourceCulture); }
        }

        internal static string LicenseStatusTrialExpiringSoon {
            get { return ResourceManager.GetString("LicenseStatusTrialExpiringSoon", resourceCulture); }
        }

        internal static string LicenseStatusTrialExpired {
            get { return ResourceManager.GetString("LicenseStatusTrialExpired", resourceCulture); }
        }

        /// <summary>
        ///   查詢類似 Please loaded at least one device! 的當地語系化字串。
        /// </summary>
        internal static string AddDeviceNonSelectionError {
            get {
                return ResourceManager.GetString("AddDeviceNonSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancelled 的當地語系化字串。
        /// </summary>
        internal static string AiCancelled {
            get {
                return ResourceManager.GetString("AiCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New Conversation 的當地語系化字串。
        /// </summary>
        internal static string AiDefaultTitle {
            get {
                return ResourceManager.GetString("AiDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tool call limit exceeded, please rephrase your question. 的當地語系化字串。
        /// </summary>
        internal static string AiMaxRoundsExceeded {
            get {
                return ResourceManager.GetString("AiMaxRoundsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AI not configured. Please enter API key in settings. 的當地語系化字串。
        /// </summary>
        internal static string AiNotConfigured {
            get {
                return ResourceManager.GetString("AiNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Send failed, please try again. 的當地語系化字串。
        /// </summary>
        internal static string AiSendFailed {
            get {
                return ResourceManager.GetString("AiSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Request timed out, please try again. 的當地語系化字串。
        /// </summary>
        internal static string AiTimeout {
            get {
                return ResourceManager.GetString("AiTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hello! I am your AI assistant. I can help analyze data, discuss business processes, or answer system-related questions. 的當地語系化字串。
        /// </summary>
        internal static string AiWelcome {
            get {
                return ResourceManager.GetString("AiWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Added 的當地語系化字串。
        /// </summary>
        internal static string ComStrAdded {
            get {
                return ResourceManager.GetString("ComStrAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Days 的當地語系化字串。
        /// </summary>
        internal static string ComStrDay {
            get {
                return ResourceManager.GetString("ComStrDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Device 的當地語系化字串。
        /// </summary>
        internal static string ComStrDevice {
            get {
                return ResourceManager.GetString("ComStrDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Downloaded 的當地語系化字串。
        /// </summary>
        internal static string ComStrDownloaded {
            get {
                return ResourceManager.GetString("ComStrDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        internal static string ComStrErrorTitle {
            get {
                return ResourceManager.GetString("ComStrErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product 的當地語系化字串。
        /// </summary>
        internal static string ComStrProduct {
            get {
                return ResourceManager.GetString("ComStrProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Removed 的當地語系化字串。
        /// </summary>
        internal static string ComStrRemoved {
            get {
                return ResourceManager.GetString("ComStrRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System User 的當地語系化字串。
        /// </summary>
        internal static string ComStrSystemUser {
            get {
                return ResourceManager.GetString("ComStrSystemUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Time Slot 的當地語系化字串。
        /// </summary>
        internal static string ComStrTimeSlot {
            get {
                return ResourceManager.GetString("ComStrTimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Uploaded 的當地語系化字串。
        /// </summary>
        internal static string ComStrUploaded {
            get {
                return ResourceManager.GetString("ComStrUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User 的當地語系化字串。
        /// </summary>
        internal static string ComStrUser {
            get {
                return ResourceManager.GetString("ComStrUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warning 的當地語系化字串。
        /// </summary>
        internal static string ComStrWarningTitle {
            get {
                return ResourceManager.GetString("ComStrWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm cancel this order? 的當地語系化字串。
        /// </summary>
        internal static string ConfirmCancelOrder {
            get {
                return ResourceManager.GetString("ConfirmCancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm end this order? 的當地語系化字串。
        /// </summary>
        internal static string ConfirmEndOrder {
            get {
                return ResourceManager.GetString("ConfirmEndOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Device Card Management 的當地語系化字串。
        /// </summary>
        internal static string DeviceCardManageDialog {
            get {
                return ResourceManager.GetString("DeviceCardManageDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Result For Current First Inspection 的當地語系化字串。
        /// </summary>
        internal static string DeviceFirstInsDialog {
            get {
                return ResourceManager.GetString("DeviceFirstInsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Chenged Materials 的當地語系化字串。
        /// </summary>
        internal static string DeviceMaterialDialog {
            get {
                return ResourceManager.GetString("DeviceMaterialDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current Operation 的當地語系化字串。
        /// </summary>
        internal static string DeviceOperationDialog {
            get {
                return ResourceManager.GetString("DeviceOperationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Result For Current Routine Inspection 的當地語系化字串。
        /// </summary>
        internal static string DeviceRoutineInsDialog {
            get {
                return ResourceManager.GetString("DeviceRoutineInsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm 的當地語系化字串。
        /// </summary>
        internal static string DialogBaseConfirm {
            get {
                return ResourceManager.GetString("DialogBaseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        internal static string DialogBaseDelete {
            get {
                return ResourceManager.GetString("DialogBaseDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        internal static string DialogBaseSave {
            get {
                return ResourceManager.GetString("DialogBaseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select an equipment first 的當地語系化字串。
        /// </summary>
        internal static string EqprodValidationEquipment {
            get {
                return ResourceManager.GetString("EqprodValidationEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No matching SOP found for the selected product and process 的當地語系化字串。
        /// </summary>
        internal static string EqprodValidationNoSop {
            get {
                return ResourceManager.GetString("EqprodValidationNoSop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a process 的當地語系化字串。
        /// </summary>
        internal static string EqprodValidationProcess {
            get {
                return ResourceManager.GetString("EqprodValidationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a product 的當地語系化字串。
        /// </summary>
        internal static string EqprodValidationProduct {
            get {
                return ResourceManager.GetString("EqprodValidationProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Seq No. must be greater than 0 的當地語系化字串。
        /// </summary>
        internal static string EqprodValidationSeqNo {
            get {
                return ResourceManager.GetString("EqprodValidationSeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This Seq No. is already used by this equipment 的當地語系化字串。
        /// </summary>
        internal static string EqprodValidationSeqNoDuplicate {
            get {
                return ResourceManager.GetString("EqprodValidationSeqNoDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 First Inspection Abnormal, please report according to procedure! 的當地語系化字串。
        /// </summary>
        internal static string InsFirstAbnormal {
            get {
                return ResourceManager.GetString("InsFirstAbnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product updated, please do first inspection! 的當地語系化字串。
        /// </summary>
        internal static string InsFirstProductUpdate {
            get {
                return ResourceManager.GetString("InsFirstProductUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 First inspection is finished! 的當地語系化字串。
        /// </summary>
        internal static string InsFirstSuccess {
            get {
                return ResourceManager.GetString("InsFirstSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Routine inspection ended! 的當地語系化字串。
        /// </summary>
        internal static string InsRoutineEnd {
            get {
                return ResourceManager.GetString("InsRoutineEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Routine inspection overdue! 的當地語系化字串。
        /// </summary>
        internal static string InsRoutineOverdue {
            get {
                return ResourceManager.GetString("InsRoutineOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Routine inspection started! 的當地語系化字串。
        /// </summary>
        internal static string InsRoutineStart {
            get {
                return ResourceManager.GetString("InsRoutineStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Routine inspection is finished! 的當地語系化字串。
        /// </summary>
        internal static string InsRoutineSuccess {
            get {
                return ResourceManager.GetString("InsRoutineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Routine lights are updated! 的當地語系化字串。
        /// </summary>
        internal static string InsRoutineUpdateLight {
            get {
                return ResourceManager.GetString("InsRoutineUpdateLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading, please wait… 的當地語系化字串。
        /// </summary>
        internal static string LoadingInitMessage {
            get {
                return ResourceManager.GetString("LoadingInitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid account or password! 的當地語系化字串。
        /// </summary>
        internal static string LogInAccountError {
            get {
                return ResourceManager.GetString("LogInAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please check the connection! 的當地語系化字串。
        /// </summary>
        internal static string LogInConnectionError {
            get {
                return ResourceManager.GetString("LogInConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please fill out completely! 的當地語系化字串。
        /// </summary>
        internal static string LogInFillOutError {
            get {
                return ResourceManager.GetString("LogInFillOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Detecting... 的當地語系化字串。
        /// </summary>
        internal static string MainProgressDetecting {
            get {
                return ResourceManager.GetString("MainProgressDetecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System is idle... 的當地語系化字串。
        /// </summary>
        internal static string MainProgressIdle {
            get {
                return ResourceManager.GetString("MainProgressIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Processing... 的當地語系化字串。
        /// </summary>
        internal static string MainProgressProcessing {
            get {
                return ResourceManager.GetString("MainProgressProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Saving... 的當地語系化字串。
        /// </summary>
        internal static string MainProgressSaving {
            get {
                return ResourceManager.GetString("MainProgressSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stopped 的當地語系化字串。
        /// </summary>
        internal static string MainProgressStopped {
            get {
                return ResourceManager.GetString("MainProgressStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finished 的當地語系化字串。
        /// </summary>
        internal static string MainProgressSuccess {
            get {
                return ResourceManager.GetString("MainProgressSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select at least one item! 的當地語系化字串。
        /// </summary>
        internal static string MaterialNonSelectionError {
            get {
                return ResourceManager.GetString("MaterialNonSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No current product 的當地語系化字串。
        /// </summary>
        internal static string NoCurrentProduct {
            get {
                return ResourceManager.GetString("NoCurrentProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Only one order can be in production 的當地語系化字串。
        /// </summary>
        internal static string OnlyOneProductionError {
            get {
                return ResourceManager.GetString("OnlyOneProductionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order Management 的當地語系化字串。
        /// </summary>
        internal static string OrderListTitle {
            get {
                return ResourceManager.GetString("OrderListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a process 的當地語系化字串。
        /// </summary>
        internal static string PioFormErrorProcess {
            get {
                return ResourceManager.GetString("PioFormErrorProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a product 的當地語系化字串。
        /// </summary>
        internal static string PioFormErrorProduct {
            get {
                return ResourceManager.GetString("PioFormErrorProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Quantity must be greater than 0 的當地語系化字串。
        /// </summary>
        internal static string PioFormErrorQty {
            get {
                return ResourceManager.GetString("PioFormErrorQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to receive, please try again 的當地語系化字串。
        /// </summary>
        internal static string PioFormSubmitError {
            get {
                return ResourceManager.GetString("PioFormSubmitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit Program Status 的當地語系化字串。
        /// </summary>
        internal static string ProgramStatusDialogTitle {
            get {
                return ResourceManager.GetString("ProgramStatusDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a status 的當地語系化字串。
        /// </summary>
        internal static string ProgramStatusNoSelectionError {
            get {
                return ResourceManager.GetString("ProgramStatusNoSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Assign Order 的當地語系化字串。
        /// </summary>
        internal static string SchAssignDialogTitle {
            get {
                return ResourceManager.GetString("SchAssignDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a SOP type 的當地語系化字串。
        /// </summary>
        internal static string SchAssignNoSopSelected {
            get {
                return ResourceManager.GetString("SchAssignNoSopSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order quantity cannot exceed remaining quantity 的當地語系化字串。
        /// </summary>
        internal static string SchAssignQtyExceeded {
            get {
                return ResourceManager.GetString("SchAssignQtyExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Max: {0} 的當地語系化字串。
        /// </summary>
        internal static string SchAssignQtyMaxHint {
            get {
                return ResourceManager.GetString("SchAssignQtyMaxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter order quantity 的當地語系化字串。
        /// </summary>
        internal static string SchAssignQtyRequired {
            get {
                return ResourceManager.GetString("SchAssignQtyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reason (optional) 的當地語系化字串。
        /// </summary>
        internal static string SchCancelOrderDescLabel {
            get {
                return ResourceManager.GetString("SchCancelOrderDescLabel", resourceCulture);
            }
        }
        internal static string SchEndTuningConfirmMessage {
            get { return ResourceManager.GetString("SchEndTuningConfirmMessage", resourceCulture); }
        }
        internal static string SchEndTuningStarted {
            get { return ResourceManager.GetString("SchEndTuningStarted", resourceCulture); }
        }
        
        /// <summary>
        ///   查詢類似 Cancel Order 的當地語系化字串。
        /// </summary>
        internal static string SchCancelOrderDialogTitle {
            get {
                return ResourceManager.GetString("SchCancelOrderDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ⚠ Cancel Notice 的當地語系化字串。
        /// </summary>
        internal static string SchDerivedBadgeCancelNotice {
            get {
                return ResourceManager.GetString("SchDerivedBadgeCancelNotice", resourceCulture);
            }
        }

        internal static string SchDerivedBadgeDevelop {
            get {
                return ResourceManager.GetString("SchDerivedBadgeDevelop", resourceCulture);
            }
        }

        internal static string SchDerivedBadgeNewProduct {
            get {
                return ResourceManager.GetString("SchDerivedBadgeNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ✓ Production Done 的當地語系化字串。
        /// </summary>
        internal static string SchDerivedBadgeComplete {
            get {
                return ResourceManager.GetString("SchDerivedBadgeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ⬟ In Production 的當地語系化字串。
        /// </summary>
        internal static string SchDerivedBadgeInProduction {
            get {
                return ResourceManager.GetString("SchDerivedBadgeInProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ⚠ Partial Done 的當地語系化字串。
        /// </summary>
        internal static string SchDerivedBadgePartial {
            get {
                return ResourceManager.GetString("SchDerivedBadgePartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel Schedule 的當地語系化字串。
        /// </summary>
        internal static string ScheduleOpCancelTitle {
            get {
                return ResourceManager.GetString("ScheduleOpCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remarks is required 的當地語系化字串。
        /// </summary>
        internal static string ScheduleOpDescRequired {
            get {
                return ResourceManager.GetString("ScheduleOpDescRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Force Complete 的當地語系化字串。
        /// </summary>
        internal static string ScheduleOpForceCompleteTitle {
            get {
                return ResourceManager.GetString("ScheduleOpForceCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Force completed by  的當地語系化字串。
        /// </summary>
        internal static string ScheduleOpForcedByPrefix {
            get {
                return ResourceManager.GetString("ScheduleOpForcedByPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        internal static string ScheduleOpForcedBySuffix {
            get {
                return ResourceManager.GetString("ScheduleOpForcedBySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Release 的當地語系化字串。
        /// </summary>
        internal static string ScheduleOpReleaseTitle {
            get {
                return ResourceManager.GetString("ScheduleOpReleaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input cannot exceed remaining quantity 的當地語系化字串。
        /// </summary>
        internal static string ScheduleOpRemainingQtyExceeded {
            get {
                return ResourceManager.GetString("ScheduleOpRemainingQtyExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Max: {0} 的當地語系化字串。
        /// </summary>
        internal static string ScheduleOpRemainingQtyHint {
            get {
                return ResourceManager.GetString("ScheduleOpRemainingQtyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remaining quantity is required 的當地語系化字串。
        /// </summary>
        internal static string ScheduleOpRemainingQtyRequired {
            get {
                return ResourceManager.GetString("ScheduleOpRemainingQtyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Split Order 的當地語系化字串。
        /// </summary>
        internal static string ScheduleOpSplitTitle {
            get {
                return ResourceManager.GetString("ScheduleOpSplitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Verify Completion 的當地語系化字串。
        /// </summary>
        internal static string ScheduleOpVerifyTitle {
            get {
                return ResourceManager.GetString("ScheduleOpVerifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancelled 的當地語系化字串。
        /// </summary>
        internal static string SchOrderStatusCancelled {
            get {
                return ResourceManager.GetString("SchOrderStatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Done 的當地語系化字串。
        /// </summary>
        internal static string SchOrderStatusCompleted {
            get {
                return ResourceManager.GetString("SchOrderStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 In Prod. 的當地語系化字串。
        /// </summary>
        internal static string SchOrderStatusInProduction {
            get {
                return ResourceManager.GetString("SchOrderStatusInProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pending 的當地語系化字串。
        /// </summary>
        internal static string SchOrderStatusPending {
            get {
                return ResourceManager.GetString("SchOrderStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Added successfully 的當地語系化字串。
        /// </summary>
        internal static string SopSuccessAdd {
            get {
                return ResourceManager.GetString("SopSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Updated successfully 的當地語系化字串。
        /// </summary>
        internal static string SopSuccessUpdate {
            get {
                return ResourceManager.GetString("SopSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit SOP (ID: {0}) 的當地語系化字串。
        /// </summary>
        internal static string SopTitleEdit {
            get {
                return ResourceManager.GetString("SopTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New SOP 的當地語系化字串。
        /// </summary>
        internal static string SopTitleNew {
            get {
                return ResourceManager.GetString("SopTitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fixture: Material is required 的當地語系化字串。
        /// </summary>
        internal static string SopValidationFixture {
            get {
                return ResourceManager.GetString("SopValidationFixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 At least 1 item is required 的當地語系化字串。
        /// </summary>
        internal static string SopValidationMinItems {
            get {
                return ResourceManager.GetString("SopValidationMinItems", resourceCulture);
            }
        }

        internal static string SopValidationDuplicate {
            get { return ResourceManager.GetString("SopValidationDuplicate", resourceCulture); }
        }

        internal static string SopTemplateOverwriteConfirm {
            get { return ResourceManager.GetString("SopTemplateOverwriteConfirm", resourceCulture); }
        }

        /// <summary>
        ///   查詢類似 Other: Content is required 的當地語系化字串。
        /// </summary>
        internal static string SopValidationOther {
            get {
                return ResourceManager.GetString("SopValidationOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Part / Model / Process are required 的當地語系化字串。
        /// </summary>
        internal static string SopValidationRequiredFields {
            get {
                return ResourceManager.GetString("SopValidationRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Station: Workstation No. and material are required 的當地語系化字串。
        /// </summary>
        internal static string SopValidationStation {
            get {
                return ResourceManager.GetString("SopValidationStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Swipe card to confirm end of tuning 的當地語系化字串。
        /// </summary>
        internal static string TuningCardConfirm {
            get {
                return ResourceManager.GetString("TuningCardConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Tuning Operation 的當地語系化字串。
        /// </summary>
        internal static string TuningDialogTitle {
            get {
                return ResourceManager.GetString("TuningDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm end Offset? 的當地語系化字串。
        /// </summary>
        internal static string TuningEndConfirmOffset {
            get {
                return ResourceManager.GetString("TuningEndConfirmOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm end Teaching? 的當地語系化字串。
        /// </summary>
        internal static string TuningEndConfirmTeaching {
            get {
                return ResourceManager.GetString("TuningEndConfirmTeaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Offset... 的當地語系化字串。
        /// </summary>
        internal static string TuningInProgressOffset {
            get {
                return ResourceManager.GetString("TuningInProgressOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Teaching... 的當地語系化字串。
        /// </summary>
        internal static string TuningInProgressTeaching {
            get {
                return ResourceManager.GetString("TuningInProgressTeaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Waited 的當地語系化字串。
        /// </summary>
        internal static string WaitedDaysForSchedule {
            get {
                return ResourceManager.GetString("WaitedDaysForSchedule", resourceCulture);
            }
        }

        internal static string SettingSuccessAdd {
            get { return ResourceManager.GetString("SettingSuccessAdd", resourceCulture); }
        }

        internal static string SettingSuccessUpdate {
            get { return ResourceManager.GetString("SettingSuccessUpdate", resourceCulture); }
        }

        internal static string SettingValidationUserIdNameRequired {
            get { return ResourceManager.GetString("SettingValidationUserIdNameRequired", resourceCulture); }
        }

        internal static string SettingValidationRoleRequired {
            get { return ResourceManager.GetString("SettingValidationRoleRequired", resourceCulture); }
        }

        internal static string SettingValidationPasswordRequired {
            get { return ResourceManager.GetString("SettingValidationPasswordRequired", resourceCulture); }
        }

        internal static string SettingValidationMaterialCodeNameRequired {
            get { return ResourceManager.GetString("SettingValidationMaterialCodeNameRequired", resourceCulture); }
        }

        internal static string SettingValidationErrorCodeRequired {
            get { return ResourceManager.GetString("SettingValidationErrorCodeRequired", resourceCulture); }
        }

        internal static string SettingValidationEquipmentCodeNameIpRequired {
            get { return ResourceManager.GetString("SettingValidationEquipmentCodeNameIpRequired", resourceCulture); }
        }

        internal static string SettingValidationPortRange {
            get { return ResourceManager.GetString("SettingValidationPortRange", resourceCulture); }
        }

        internal static string SettingValidationRoleNameRequired {
            get { return ResourceManager.GetString("SettingValidationRoleNameRequired", resourceCulture); }
        }

        internal static string SettingValidationTimeSlotEndTime {
            get { return ResourceManager.GetString("SettingValidationTimeSlotEndTime", resourceCulture); }
        }

        internal static string SopValidationNotFound {
            get { return ResourceManager.GetString("SopValidationNotFound", resourceCulture); }
        }

        internal static string HwValidationTrueFalse {
            get { return ResourceManager.GetString("HwValidationTrueFalse", resourceCulture); }
        }

        internal static string HwValidationIntRange {
            get { return ResourceManager.GetString("HwValidationIntRange", resourceCulture); }
        }

        internal static string HwSelectComPort {
            get { return ResourceManager.GetString("HwSelectComPort", resourceCulture); }
        }

        internal static string HwConnected {
            get { return ResourceManager.GetString("HwConnected", resourceCulture); }
        }

        internal static string HwConnectionFailed {
            get { return ResourceManager.GetString("HwConnectionFailed", resourceCulture); }
        }

        internal static string HwSelectControllerOrIp {
            get { return ResourceManager.GetString("HwSelectControllerOrIp", resourceCulture); }
        }

        internal static string HwDisconnected {
            get { return ResourceManager.GetString("HwDisconnected", resourceCulture); }
        }

        internal static string HwAutoModeWriteDisabled {
            get { return ResourceManager.GetString("HwAutoModeWriteDisabled", resourceCulture); }
        }

        internal static string HwWriteSuccess {
            get { return ResourceManager.GetString("HwWriteSuccess", resourceCulture); }
        }

        internal static string HwValidationNumericRequired {
            get { return ResourceManager.GetString("HwValidationNumericRequired", resourceCulture); }
        }

        internal static string HwControllersFound {
            get { return ResourceManager.GetString("HwControllersFound", resourceCulture); }
        }

        internal static string HwConfirmModbusWrite {
            get { return ResourceManager.GetString("HwConfirmModbusWrite", resourceCulture); }
        }

        internal static string HwConfirmAbbWrite {
            get { return ResourceManager.GetString("HwConfirmAbbWrite", resourceCulture); }
        }

        internal static string HwConfirmWriteTitle {
            get { return ResourceManager.GetString("HwConfirmWriteTitle", resourceCulture); }
        }

        internal static string HwAbbConnected {
            get { return ResourceManager.GetString("HwAbbConnected", resourceCulture); }
        }

        internal static string HwControllerNotFound {
            get { return ResourceManager.GetString("HwControllerNotFound", resourceCulture); }
        }

        internal static string HwAbbConnectionFailed {
            get { return ResourceManager.GetString("HwAbbConnectionFailed", resourceCulture); }
        }

        internal static string HwReadVariableFailed {
            get { return ResourceManager.GetString("HwReadVariableFailed", resourceCulture); }
        }

        internal static string HwRapidValueReadFailed {
            get { return ResourceManager.GetString("HwRapidValueReadFailed", resourceCulture); }
        }

        internal static string HwReadFailed {
            get { return ResourceManager.GetString("HwReadFailed", resourceCulture); }
        }

        internal static string HwWriteFailed {
            get { return ResourceManager.GetString("HwWriteFailed", resourceCulture); }
        }

        internal static string SsUploadSuccess {
            get { return ResourceManager.GetString("SsUploadSuccess", resourceCulture); }
        }

        internal static string SopDisplayStation {
            get { return ResourceManager.GetString("SopDisplayStation", resourceCulture); }
        }

        internal static string SopDisplayFixture {
            get { return ResourceManager.GetString("SopDisplayFixture", resourceCulture); }
        }

        internal static string SopDisplayQuantity {
            get { return ResourceManager.GetString("SopDisplayQuantity", resourceCulture); }
        }

        internal static string SopDisplayManHour {
            get { return ResourceManager.GetString("SopDisplayManHour", resourceCulture); }
        }

        internal static string ComStrNone {
            get { return ResourceManager.GetString("ComStrNone", resourceCulture); }
        }

        internal static string MesSyncDialog_Title {
            get { return ResourceManager.GetString("MesSyncDialog_Title", resourceCulture); }
        }

        internal static string MesSyncState_Synced {
            get { return ResourceManager.GetString("MesSyncState_Synced", resourceCulture); }
        }

        internal static string MesSyncState_MesOnly {
            get { return ResourceManager.GetString("MesSyncState_MesOnly", resourceCulture); }
        }

        internal static string MesSyncState_LocalOnly {
            get { return ResourceManager.GetString("MesSyncState_LocalOnly", resourceCulture); }
        }

        internal static string MesSyncState_DataMismatch {
            get { return ResourceManager.GetString("MesSyncState_DataMismatch", resourceCulture); }
        }

        internal static string ChartFieldEquipmentName {
            get { return ResourceManager.GetString("ChartFieldEquipmentName", resourceCulture); }
        }

        internal static string ChartFieldProductionStatus {
            get { return ResourceManager.GetString("ChartFieldProductionStatus", resourceCulture); }
        }

        internal static string ChartFieldLoadLevel {
            get { return ResourceManager.GetString("ChartFieldLoadLevel", resourceCulture); }
        }

        internal static string ChartFieldTuningStatus {
            get { return ResourceManager.GetString("ChartFieldTuningStatus", resourceCulture); }
        }

        internal static string ChartFieldActiveOrderCount {
            get { return ResourceManager.GetString("ChartFieldActiveOrderCount", resourceCulture); }
        }

        internal static string ChartFieldTotalPendingQty {
            get { return ResourceManager.GetString("ChartFieldTotalPendingQty", resourceCulture); }
        }

        internal static string ChartFieldFeasibleProgramCount {
            get { return ResourceManager.GetString("ChartFieldFeasibleProgramCount", resourceCulture); }
        }

        internal static string ChartFieldTotalProgramCount {
            get { return ResourceManager.GetString("ChartFieldTotalProgramCount", resourceCulture); }
        }

        internal static string ChartFieldCurrentProduct {
            get { return ResourceManager.GetString("ChartFieldCurrentProduct", resourceCulture); }
        }

        internal static string ChartFieldProgressCompleted {
            get { return ResourceManager.GetString("ChartFieldProgressCompleted", resourceCulture); }
        }

        internal static string ChartFieldProgressTarget {
            get { return ResourceManager.GetString("ChartFieldProgressTarget", resourceCulture); }
        }

        internal static string ChartFieldScheduleId {
            get { return ResourceManager.GetString("ChartFieldScheduleId", resourceCulture); }
        }

        internal static string ChartFieldBrand {
            get { return ResourceManager.GetString("ChartFieldBrand", resourceCulture); }
        }

        internal static string ChartFieldPartNo {
            get { return ResourceManager.GetString("ChartFieldPartNo", resourceCulture); }
        }

        internal static string ChartFieldModel {
            get { return ResourceManager.GetString("ChartFieldModel", resourceCulture); }
        }

        internal static string ChartFieldProcess {
            get { return ResourceManager.GetString("ChartFieldProcess", resourceCulture); }
        }

        internal static string ChartFieldQuantity {
            get { return ResourceManager.GetString("ChartFieldQuantity", resourceCulture); }
        }

        internal static string ChartFieldActualQuantity {
            get { return ResourceManager.GetString("ChartFieldActualQuantity", resourceCulture); }
        }

        internal static string ChartFieldStatus {
            get { return ResourceManager.GetString("ChartFieldStatus", resourceCulture); }
        }

        internal static string ChartFieldSopType {
            get { return ResourceManager.GetString("ChartFieldSopType", resourceCulture); }
        }

        internal static string ChartFieldReceivedAt {
            get { return ResourceManager.GetString("ChartFieldReceivedAt", resourceCulture); }
        }

        internal static string ChartFieldWaitingDays {
            get { return ResourceManager.GetString("ChartFieldWaitingDays", resourceCulture); }
        }

        internal static string ChartFieldActiveEquipmentCount {
            get { return ResourceManager.GetString("ChartFieldActiveEquipmentCount", resourceCulture); }
        }

        internal static string ChartValInProduction {
            get { return ResourceManager.GetString("ChartValInProduction", resourceCulture); }
        }

        internal static string ChartValPendingProd {
            get { return ResourceManager.GetString("ChartValPendingProd", resourceCulture); }
        }

        internal static string ChartValIdle {
            get { return ResourceManager.GetString("ChartValIdle", resourceCulture); }
        }

        internal static string ChartValUnavailable {
            get { return ResourceManager.GetString("ChartValUnavailable", resourceCulture); }
        }

        internal static string ChartValLoadNone {
            get { return ResourceManager.GetString("ChartValLoadNone", resourceCulture); }
        }

        internal static string ChartValLoadLow {
            get { return ResourceManager.GetString("ChartValLoadLow", resourceCulture); }
        }

        internal static string ChartValLoadMid {
            get { return ResourceManager.GetString("ChartValLoadMid", resourceCulture); }
        }

        internal static string ChartValLoadHigh {
            get { return ResourceManager.GetString("ChartValLoadHigh", resourceCulture); }
        }

        internal static string ChartValTuningNone {
            get { return ResourceManager.GetString("ChartValTuningNone", resourceCulture); }
        }

        internal static string ChartValTuningActive {
            get { return ResourceManager.GetString("ChartValTuningActive", resourceCulture); }
        }

        internal static string ChartValSchPending {
            get { return ResourceManager.GetString("ChartValSchPending", resourceCulture); }
        }

        internal static string ChartValSchScheduled {
            get { return ResourceManager.GetString("ChartValSchScheduled", resourceCulture); }
        }

        internal static string ChartValSchCompleted {
            get { return ResourceManager.GetString("ChartValSchCompleted", resourceCulture); }
        }

        internal static string ChartValSchReleased {
            get { return ResourceManager.GetString("ChartValSchReleased", resourceCulture); }
        }

        internal static string ChartValSchCancelled {
            get { return ResourceManager.GetString("ChartValSchCancelled", resourceCulture); }
        }

        internal static string ChartValSopDevelop {
            get { return ResourceManager.GetString("ChartValSopDevelop", resourceCulture); }
        }

        internal static string ChartValSopOpen {
            get { return ResourceManager.GetString("ChartValSopOpen", resourceCulture); }
        }

        internal static string ChartValSopClose {
            get { return ResourceManager.GetString("ChartValSopClose", resourceCulture); }
        }

        internal static string ChartValSopACME {
            get { return ResourceManager.GetString("ChartValSopACME", resourceCulture); }
        }

        internal static string ChartValSopTC {
            get { return ResourceManager.GetString("ChartValSopTC", resourceCulture); }
        }

        internal static string ChartValSopOther {
            get { return ResourceManager.GetString("ChartValSopOther", resourceCulture); }
        }

        internal static string ChartDefaultEquipmentOverview {
            get { return ResourceManager.GetString("ChartDefaultEquipmentOverview", resourceCulture); }
        }

        internal static string ChartDefaultScheduleBoard {
            get { return ResourceManager.GetString("ChartDefaultScheduleBoard", resourceCulture); }
        }

        internal static string ChartStatEquipmentTotal {
            get { return ResourceManager.GetString("ChartStatEquipmentTotal", resourceCulture); }
        }

        internal static string ChartStatScheduleTotal {
            get { return ResourceManager.GetString("ChartStatScheduleTotal", resourceCulture); }
        }

        internal static string ChartStatInProductionCount {
            get { return ResourceManager.GetString("ChartStatInProductionCount", resourceCulture); }
        }

        internal static string ChartStatTuningActiveCount {
            get { return ResourceManager.GetString("ChartStatTuningActiveCount", resourceCulture); }
        }

        internal static string ChartStatIdleCount {
            get { return ResourceManager.GetString("ChartStatIdleCount", resourceCulture); }
        }

        internal static string ChartBtnHighLoad {
            get { return ResourceManager.GetString("ChartBtnHighLoad", resourceCulture); }
        }

        internal static string ChartBtnIdle {
            get { return ResourceManager.GetString("ChartBtnIdle", resourceCulture); }
        }

        internal static string ChartFilterAll {
            get { return ResourceManager.GetString("ChartFilterAll", resourceCulture); }
        }

        internal static string ChartDesignerSanitizedNotice {
            get { return ResourceManager.GetString("ChartDesignerSanitizedNotice", resourceCulture); }
        }

        internal static string ChartDataSetEquipment {
            get { return ResourceManager.GetString("ChartDataSetEquipment", resourceCulture); }
        }

        internal static string ChartDataSetSchedule {
            get { return ResourceManager.GetString("ChartDataSetSchedule", resourceCulture); }
        }

        internal static string ChartDataSetSwitchConfirm {
            get { return ResourceManager.GetString("ChartDataSetSwitchConfirm", resourceCulture); }
        }

        internal static string ChartAggregateCount {
            get { return ResourceManager.GetString("ChartAggregateCount", resourceCulture); }
        }

        internal static string ChartAggregateSum {
            get { return ResourceManager.GetString("ChartAggregateSum", resourceCulture); }
        }

        internal static string ChartStatFieldAllRows {
            get { return ResourceManager.GetString("ChartStatFieldAllRows", resourceCulture); }
        }

        internal static string ChartFilterValueNone {
            get { return ResourceManager.GetString("ChartFilterValueNone", resourceCulture); }
        }

        internal static string ChartDefaultSortByTitle {
            get { return ResourceManager.GetString("ChartDefaultSortByTitle", resourceCulture); }
        }

        internal static string ChartContainerCard {
            get { return ResourceManager.GetString("ChartContainerCard", resourceCulture); }
        }

        internal static string ChartContainerTable {
            get { return ResourceManager.GetString("ChartContainerTable", resourceCulture); }
        }

        internal static string ChartContainerMap {
            get { return ResourceManager.GetString("ChartContainerMap", resourceCulture); }
        }

        internal static string ChartContainerGraph {
            get { return ResourceManager.GetString("ChartContainerGraph", resourceCulture); }
        }

        internal static string ChartValidationNameRequired {
            get { return ResourceManager.GetString("ChartValidationNameRequired", resourceCulture); }
        }

        internal static string ChartValidationNameDuplicate {
            get { return ResourceManager.GetString("ChartValidationNameDuplicate", resourceCulture); }
        }

        internal static string ChartValidationTitleFieldRequired {
            get { return ResourceManager.GetString("ChartValidationTitleFieldRequired", resourceCulture); }
        }

        internal static string ChartValidationTableColumnsRequired {
            get { return ResourceManager.GetString("ChartValidationTableColumnsRequired", resourceCulture); }
        }

        internal static string ChartDeleteConfirm {
            get { return ResourceManager.GetString("ChartDeleteConfirm", resourceCulture); }
        }

        internal static string PlBulkStatusConfirm {
            get { return ResourceManager.GetString("PlBulkStatusConfirm", resourceCulture); }
        }
    }
}
