<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<Platforms>AnyCPU;x64</Platforms>
		<ApplicationIcon>appIcon.ico</ApplicationIcon>

		<!-- 正式版發佈前確認伺服器: LOGIN SERVER -->
		<AssemblyVersion>3.3.0.1</AssemblyVersion>
		<FileVersion>3.3.0.1</FileVersion>
		<Version>3.3.0</Version>
		<!-- 禁用將 Git Commit ID 加入 InformationalVersion -->
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Properties\PublishProfiles\**" />
	  <EmbeddedResource Remove="Properties\PublishProfiles\**" />
	  <None Remove="Properties\PublishProfiles\**" />
	  <Page Remove="Properties\PublishProfiles\**" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="appsettings.json" />
		<None Remove="Resources\social-connections256.png" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
		<SplashScreen Include="Resources\social-connections256.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</SplashScreen>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.24" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
		<Resource Include="appIcon.ico" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Dapper" Version="2.1.72" />
		<PackageReference Include="MaterialDesignColors" Version="5.3.0" />
		<PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.24" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.24" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.IO.Ports" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
			<CustomToolNamespace></CustomToolNamespace>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Content Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<None Update="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DeviceDrivers.Abb\DeviceDrivers.Abb.csproj" />
		<ProjectReference Include="..\DeviceDrivers.Modbus\DeviceDrivers.Modbus.csproj" />
	</ItemGroup>

</Project>
