using FProductionDashBoard.Models;
using FProductionDashBoard.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Linq;
using Xunit;

namespace FProductionDashBoard.Tests.Models
{
    // MesDbContext 模型對應測試：建 context 後存取 ctx.Model 即觸發 EF 模型 build，
    // 不連線、不執行 SQL；用 dummy 連線字串即可。
    public class ProductSopModelTests
    {
        private static MesDbContext CreateContext()
        {
            var options = new DbContextOptionsBuilder<MesDbContext>()
                .UseSqlServer("Server=.;Database=dummy;Trusted_Connection=True;")
                .Options;
            return new MesDbContext(options);
        }

        [Fact]
        public void MesDbContext_ModelBuilds_Successfully()
        {
            using var ctx = CreateContext();
            var model = ctx.Model;
            Assert.NotNull(model);
            // 任意實體都應該被 EF 識別
            Assert.NotEmpty(model.GetEntityTypes());
        }

        [Theory]
        [InlineData(typeof(ProductPart), "product_part")]
        [InlineData(typeof(ProductModel), "product_model")]
        [InlineData(typeof(WorkProcess), "work_process")]
        [InlineData(typeof(Product), "product")]
        [InlineData(typeof(SopChecklist), "sop_checklist")]
        [InlineData(typeof(SopChecklistItem), "sop_checklist_item")]
        [InlineData(typeof(EquipmentProduct), "equipment_product")]
        public void Entity_Maps_To_Expected_Table(System.Type clrType, string expectedTable)
        {
            using var ctx = CreateContext();
            var entity = ctx.Model.FindEntityType(clrType);
            Assert.NotNull(entity);
            Assert.Equal(expectedTable, entity!.GetTableName());
        }

        [Theory]
        [InlineData(typeof(ProductPart), nameof(ProductPart.PartId), "part_id")]
        [InlineData(typeof(ProductPart), nameof(ProductPart.PartNo), "part_no")]
        [InlineData(typeof(ProductModel), nameof(ProductModel.ModelId), "model_id")]
        [InlineData(typeof(WorkProcess), nameof(WorkProcess.ProcessId), "process_id")]
        [InlineData(typeof(WorkProcess), nameof(WorkProcess.ErpCode), "erp_code")]
        [InlineData(typeof(Product), nameof(Product.ProductId), "product_id")]
        [InlineData(typeof(Product), nameof(Product.PartId), "part_id")]
        [InlineData(typeof(Product), nameof(Product.ModelId), "model_id")]
        [InlineData(typeof(SopChecklist), nameof(SopChecklist.SopId), "sop_id")]
        [InlineData(typeof(SopChecklist), nameof(SopChecklist.ProcessId), "process_id")]
        [InlineData(typeof(SopChecklist), nameof(SopChecklist.SopType), "sop_type")]
        [InlineData(typeof(SopChecklistItem), nameof(SopChecklistItem.ItemId), "item_id")]
        [InlineData(typeof(SopChecklistItem), nameof(SopChecklistItem.CheckType), "check_type")]
        [InlineData(typeof(SopChecklistItem), nameof(SopChecklistItem.WorkstationNo), "workstation_no")]
        [InlineData(typeof(SopChecklistItem), nameof(SopChecklistItem.MaterialId), "material_id")]
        [InlineData(typeof(EquipmentProduct), nameof(EquipmentProduct.EquipmentProductId), "equipment_product_id")]
        [InlineData(typeof(EquipmentProduct), nameof(EquipmentProduct.SeqNo), "seq_no")]
        [InlineData(typeof(EquipmentProduct), nameof(EquipmentProduct.SopId), "sop_id")]
        public void Property_Maps_To_Expected_Column(System.Type clrType, string propertyName, string expectedColumn)
        {
            using var ctx = CreateContext();
            var entity = ctx.Model.FindEntityType(clrType);
            Assert.NotNull(entity);
            var prop = entity!.FindProperty(propertyName);
            Assert.NotNull(prop);
            var storeId = StoreObjectIdentifier.Table(entity.GetTableName()!, entity.GetSchema());
            Assert.Equal(expectedColumn, prop!.GetColumnName(storeId));
        }

        [Theory]
        [InlineData(typeof(WorkProcess), nameof(WorkProcess.ProcessId))]
        public void TypeLookup_Key_Is_Not_AutoGenerated(System.Type clrType, string keyName)
        {
            using var ctx = CreateContext();
            var entity = ctx.Model.FindEntityType(clrType);
            Assert.NotNull(entity);
            var prop = entity!.FindProperty(keyName);
            Assert.NotNull(prop);
            // 人為定義鍵：ValueGenerated 須為 Never
            Assert.Equal(ValueGenerated.Never, prop!.ValueGenerated);
        }

        [Theory]
        [InlineData(typeof(SopChecklist), nameof(SopChecklist.SopType))]
        [InlineData(typeof(SopChecklistItem), nameof(SopChecklistItem.CheckType))]
        public void Enum_Property_Is_Stored_As_String(System.Type clrType, string propertyName)
        {
            using var ctx = CreateContext();
            var entity = ctx.Model.FindEntityType(clrType);
            Assert.NotNull(entity);
            var prop = entity!.FindProperty(propertyName);
            Assert.NotNull(prop);
            Assert.Equal(typeof(string), prop!.GetProviderClrType() ?? prop.ClrType);
        }
    }
}
